spring:
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/microshopping?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: chen1436863821
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

# swagger开关 打开true/关闭false
swagger:
    enable: true

# Jwt相关
audience:
    clientId: d2Vmdw==
    base64Secret: OTF6MjM0OTh5dGhncmlnZWhhbmdkYWVyZ2VyZ24=
    name: geemu
    expiresSecond: 604800 # 七天

security:
  basic:
    enabled: false