driverClass: com.mysql.cj.jdbc.Driver
connectionURL: jdbc:mysql://localhost:3306/secondaryDataBase?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
userId: root
password: chen1436863821

mapperPackage: com.chenfangming.persistence.dao.secondary
modelPackage: com.chenfangming.persistence.model.secondary
sqlMapperPackage: mapper.secondary
src_main_java: src/main/java
src_main_resources: src/main/resources