server:
  port: 8761
  
spring:
    application:
        name: eureka
        #JSON 日期格式
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    # 环境 开发dev|测试test|预生产pre|生产pro
    profiles:
        active: dev

security:
  basic:
    enabled: false # 开启认证
  user:
    name: user # 用户名
    password: 123456 # 密码

management:
  security:
    enabled: false



