server:
  port: 8761

banner:
  charset: UTF-8

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
  # 表明自己是一个eureka server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/register/