eureka:
  instance:
    preferIpAddress: true
  server:
    enableSelfPreservation: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://172.16.10.23:8761/eureka/