server:
  port: 8081

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname:  eureka
    preferIpAddress: true
  server:
    enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
