driverClass: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/microshopping?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
user: root
password: chen1436863821
project: src/main/java
resources: src/main/resources
modelPackage: me.geemu.persistence.model.primary
# 生成的mapper接口类所在包
mapperPackage: me.geemu.persistence.dao.primary
# 生成的mapper xml文件所在包，默认存储在resources目录下
sqlMapperPackage: mapper.primary



