spring:
  profiles:
    active: dev
  application:
          name: pass_tool
  jackson:
          serialization.write_dates_as_timestamps: false
  datasource:
    url: jdbc:mysql://localhost:3306/geemu?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: chen1436863821
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    # 标明注册中心的地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 端口号
server:
    port: 8762
    tomcat:
        max-threads: 1000
        url-encoding: UTF-8

# swagger开关 打开true/关闭false
swagger:
    enable: true

# 日志
logging:
    config: classpath:logback.xml