driverClass: com.mysql.cj.jdbc.Driver
connectionURL: jdbc:mysql://103.72.166.244:3306/primaryDataBase?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
userId: chenfangming
password: chenfangming

mapperPackage: me.geemu.persistence.dao.secondary
modelPackage: me.geemu.persistence.model.secondary
sqlMapperPackage: mapper.secondary